version: "3.8"
services:
  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  postgres:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  node:
    image: node:20.0.0-alpine
    restart: unless-stopped
    environment:
      PORT: ${NODE_PORT}
      MONGO_URI: ${MONGO_URI}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "${NODE_PORT}:${NODE_PORT}"
    volumes:
      - ./backend:/home/node/app
    working_dir: /home/node/app
    command: sh -c "npm install && npm run dev"
    depends_on:
      - postgres
      - mongo

  vue:
    image: node:20.0.0-alpine
    restart: unless-stopped
    user: root
    working_dir: /home/node
    command: sh -c "npm install && npm run dev -- --port 8000 --host 0.0.0.0"
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/home/node

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres

volumes:
  mongo-data: {}
  postgres-data: {}
